// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvlfbzfgvwtmhufmusra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bGZiemZndnd0bWh1Zm11c3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTM2NzgsImV4cCI6MjA3Mjk4OTY3OH0.NDJvkhVlHBZ7PqP9D7OBgg3eKY761j_BLh8PfyiYnNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});